// Code generated by Wire. DO NOT EDIT.

//go:generate go run github.com/google/wire/cmd/wire
//go:build !wireinject
// +build !wireinject

package di

import (
	"go-wire-architecture/pkg/config"
	"go-wire-architecture/pkg/db"
	"go-wire-architecture/pkg/handler"
	"go-wire-architecture/pkg/handler/repository"
	"go-wire-architecture/pkg/server"
	"go-wire-architecture/pkg/server/controllers"
)

// Injectors from wire.go:

func InitializeAPI(cfg config.Config) (*server.ServerHTTP, error) {
	gormDB, err := db.ConnectDatabase(cfg)
	if err != nil {
		return nil, err
	}
	userRepository := repository.NewUserRepository(gormDB)
	userService := handler.NewUserHandler(userRepository)
	userController := controllers.NewUserController(userService)
	secondUserController := controllers.NewSecondUserController(userService)
	serverHTTP := server.NewServerHTTP(userController, secondUserController)
	return serverHTTP, nil
}
